[package]
name = "magic-wormhole"
version = "0.0.3-alpha.0"
authors = ["Brian Warner <warner@lothar.com>"]
license = "MIT"
homepage = "http://magic-wormhole.io/"
repository = "https://github.com/warner/magic-wormhole.rs"
edition = "2018"
description = "Get things from one computer to another, safely"
readme = "README.md"

# the MSRV is: rust-1.42.0
# * rustyline-derive-0.3.1 needs 1.42: 'use proc_macro' without 'extern crate proc_macro'
# * rustyline-6.0 needs 1.40: #[non_exhaustive]
# * xsalsa20poly1305-0.3.1 needs 1.37: copy_within
# * sodiumoxide-0.2.4 needs 1.36: mem::MaybeUninit

[badges]
travis-ci = { repository = "warner/magic-wormhole.rs" }

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
xsalsa20poly1305 = "0.6"
spake2 = "0.2.0"
sha2 = "0.9.1"
hkdf = "0.9.0"
hex = "0.4"
rand = "0.7"
regex = "1.4.1"
log = "0.4"
zeroize = { version = "1.1", features = ["zeroize_derive"] }
sodiumoxide = "0.2.6"
pnet = "0.26.0"
byteorder = "1.3.4"
anyhow = "1.0.33"
futures = { version = "0.3.6"}
async-std = { version = "1.6.5", features = ["attributes"] }
async-tungstenite = { version = "0.10.0", features = ["async-std-runtime"] }

# for "bin" feature
clap = { version = "2.33.3", optional = true }
env_logger = { version = "0.8.1", optional = true }

# for some tests
[dev-dependencies]
env_logger = "0.8.1"

[[bin]]
name = "wormhole"
path = "src/bin/main.rs"
required-features = ["clap", "env_logger"]

[profile.release]
overflow-checks = true
